### ISSUE TITLE
No notification shown

### ISSUE THREAD

**Issue by Fonger** [JimmyPun610/XamarinAndroidJiGuangPushNotification#1]
Hi, thank you for your great work.

After receiving a broadcast, my Application Output (log) shows the following message.
"gogoogogo" is the message I sent in the Jiguang Developer Console.
However, the notification doesn't appear in Android. Why?

```
[JIGUANG-JPush] {"n_builder_id":0,"ad_id":"2735736190","n_only":1,"m_content":{"n_content":"gogoogogo","n_style":0,"n_extras":{},"ad_t":0,"n_priority":0,"n_alert_type":7,"n_title":"","n_category":"","n_flag":1},"show_type":4} - JResponse{code=0}
[JIGUANG-JCore] [NetworkingClient] Received bytes - len:292, connection:178, pkg:com.xxx.FormApp
[JIGUANG-JCore] [NetworkingClient] Network listening...
[JIGUANG-JPush] [NotificationHelper] running flag:false
[JIGUANG-JPush] [NotificationHelper] Send push received broadcast to developer defined receiver
[JIGUANG-JCore] [PushReceiver] onReceive - cn.jpush.android.intent.NOTIFICATION_RECEIVED
[JIGUANG-JPush] [PushReceiverCore] onReceive - cn.jpush.android.intent.NOTIFICATION_RECEIVED
[JIGUANG-JCore] [HttpHelper] status code:200
[JIGUANG-JCore] [HttpHelper] status code:200
```

**Comment by JimmyPun610** [comment]
Hi,

Did the app jump into 
public override void OnReceive(Context context, Intent intent) in NotificationReceiver class?
when using debug mode?

Regards,
Jimmy Pun

**Comment by Fonger** [comment]
@JimmyPun610 Yes.


[JIGUANG-JPush] {"n_builder_id":0,"ad_id":"2753171272","n_only":1,"m_content":{"n_content":"test","n_style":0,"n_extras":{},"ad_t":0,"n_priority":0,"n_alert_type":7,"n_title":"","n_category":"","n_flag":1},"show_type":4} - JResponse{code=0}
[JIGUANG-JCore] [NetworkingClient] Received bytes - len:292, connection:215, pkg:com.xxx.FormApp
[JIGUANG-JCore] [NetworkingClient] Network listening...
[JIGUANG-JPush] [NotificationHelper] running flag:false
[JIGUANG-JPush] [NotificationHelper] Send push received broadcast to developer defined receiver
[JIGUANG-JCore] [PushReceiver] onReceive - cn.jpush.android.intent.NOTIFICATION_RECEIVED
[JIGUANG-JPush] [PushReceiverCore] onReceive - cn.jpush.android.intent.NOTIFICATION_RECEIVED
***[OnReceive] cn.jpush.android.intent.NOTIFICATION_RECEIVED***
[JIGUANG-JCore] [HttpHelper] status code:200
[JIGUANG-JCore] [HttpHelper] status code:200
Thread finished: <Thread Pool> #3


```csharp
using System;
using Android.App;
using Android.Content;
using Android.OS;
using CN.Jpush.Android.Service;
using CN.Jpush.Android.Api;
using Android.Util;

namespace FormApp.Droid
{
    [BroadcastReceiver]
    [IntentFilter(new string[] { "cn.jpush.android.intent.REGISTRATION" }, Categories = new string[] { "com.xxx.FormApp" })]
    [IntentFilter(new string[] { "cn.jpush.android.intent.MESSAGE_RECEIVED" }, Categories = new string[] { "com.xxx.FormApp" })]
    [IntentFilter(new string[] { "cn.jpush.android.intent.NOTIFICATION_RECEIVED" }, Categories = new string[] { "com.xxx.FormApp" })]
    [IntentFilter(new string[] { "cn.jpush.android.intent.NOTIFICATION_OPENED" }, Categories = new string[] { "com.xxx.FormApp" })]
    [IntentFilter(new string[] { "cn.jpush.android.intent.CONNECTION" }, Categories = new string[] { "com.xxx.FormApp" })]
    class NotificationReceiver : PushReceiver
    {
        public override void OnReceive(Context context, Intent intent)
        {
            base.OnReceive(context, intent);
            if (intent.Action == JPushInterface.ActionNotificationOpened)
            {
                //When user tap the notification on notification center
                Bundle bundle = intent.Extras;
                string jsonData = bundle.GetString(JPushInterface.ExtraExtra);
            }
            if (intent.Action == JPushInterface.ActionRegistrationId)
            {
                //Only call when first launch, get the registrationID
                string regID = JPushInterface.GetRegistrationID(context);
            }
            Log.Debug("OnReceive", intent.Action);
        }
    }

}
```

**Comment by JimmyPun610** [comment]
The json looks good. and the onReceive part is triggered.
If you still do see the notification, it might be blocked by OS. 
Did you check the Settings->Notification->Your Application?

**Comment by JimmyPun610** [comment]
As no response any more. Closed
