### ISSUE TITLE
Do you have new update version?

### ISSUE THREAD

**Issue by holopekochan** [JimmyPun610/XamarinAndroidJiGuangPushNotification#2]
Currently, JPush has  3.3.4 android SDK.
Do you have the DLL for 3.3.4 version?

**Comment by JimmyPun610** [comment]
I do not use this library for a long time sorry

**Comment by JimmyPun610** [comment]
> Currently, JPush has 3.3.4 android SDK.
> Do you have the DLL for 3.3.4 version?

Hi, I just updated the version to 3.3.6.
Also a Xamarin Form example in another github
