### ISSUE TITLE
attribute 'android:name' in <service> tag must be a valid Java class name

### ISSUE THREAD

**Issue by gfs369** [JimmyPun610/XamarinAndroidJiGuangPushNotification#3]
您好，参照您的文档，我配置了xml，把MyJCommonService、MyJPushMessageReceiver这两个类放在了xxx.Android这个项目下了，因此文档中{ProjectNamespace}我配置的是xxx.Droid，但是运行起来有如下错误，请问是什么问题？

attribute 'android:name' in <service> tag must be a valid Java class name

![image](https://user-images.githubusercontent.com/14797877/81883302-6c866900-95c7-11ea-9d73-f927df884e6c.png)

**Comment by JimmyPun610** [comment]
Hi,

I am not updating this library any more.
But for your case, it may related to your project namespace or something updated in their new version which means you need to follow their latest version settings.

FYI
https://stackoverflow.com/questions/54145312/androidname-in-activity-tag-must-be-a-valid-java-class-name-in-react-native

**Comment by gfs369** [comment]
谢谢



---Original---
